name: "Hello World"
description: "Greet someone and record the time"

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Show files before
        run: ls -la

      - name: Create File
        run: node index.js

      - name: Show files after
        run: |
          ls -la
          ls data -la

      - name: Format file
        run: npx prettier . --write

      - name: Test diffs
        run: |
          changed_files=$(git diff --name-only -r HEAD^1 HEAD)
          for file in $changed_files; do
            for watched_file in "${watched_files[@]}"; do
              if [[ $file == *"$watched_file"* ]]; then
                echo "File Changed"
              fi
            done
          done

      - name: Commit file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: 'data/default-data.json'

      - name: Warn on file changed
        run: |
          # Define the list of filenames to watch for changes
          watched_files=("data/default-data.json")
        
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            changed_files=$(git diff --name-only -r HEAD^1 HEAD)
          else
            changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
          fi

          for file in $changed_files; do
            for watched_file in "${watched_files[@]}"; do
              if [[ $file == *"$watched_file"* ]]; then
                echo "File Changed"
              fi
            done
          done
