name: "Hello World"
description: "Greet someone and record the time"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Create File
        run: node index.js

      - name: Format file
        run: npx prettier . --write

      - name: Commit file
        uses: stefanzweifel/git-auto-commit-action@v5
        id: auto-commit-action
        with:
          file_pattern: "data/default-data*.json"

      - name: "Run if changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: echo "Changes!"

      - name: "Run if no changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        run: echo "No Changes!"
